### ISSUE TITLE
Nice-to-have: location as sensor input

### ISSUE THREAD

**Issue by aurelio1** [vbier/habpanelviewer#56]
It would be great being able to access the device location with OpenHAB, e.g. to deactivate certain actions/alarms when the device is at home.
It would be crucial that the location detection does not use Google Play, but some other API eg used also in [OsmAnd](https://github.com/osmandapp) in the [Location Listener](https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/OsmAndLocationProvider.java).

**Comment by MDAR** [comment]
Not strictly something to add into Habpanelviewer, so this is just a suggestion.

Have you seen / used this app ?

https://community.openhab.org/t/locator-app-with-rest-api/71342/


I like it because it doesn't (need to) call home to its own server every time to take a step.

Rather it makes its own decision on its GeoFence location and just changes the State of two Items in openHAB2, either using the local IP or via myopenhab.org
(Both sets of details are saved in the app, so it can select the quickest connection route)

Something similar would be a nice feature to add to Habpanelviewer, but as 'most' people seem to be using the app on wall mounted devices, I don't understand how such a feature would be useful.
(Please educate me if you have a clever use case)

**Comment by aurelio1** [comment]
MDAR thank you for the link - I had searched for something like that, but not found this one. It seems to be a good replacement, and I will try to use it.
I use habpanelviewer as main app to access my home environment. Yes, I also use it for a wall mounted device, but also for my mobile device. On my mobile device, I use it to switch on and off alarm when leaving / coming home, to check my cams and occasionally to switch off the lights if my cleaning person has forgotten to do that. And for this alarm setting it would be great to leave that to the app.
I will check how I can do the same with the App you linked to.

**Comment by aurelio1** [comment]
@MDAR Unfortunately, the locator app insists on having Google Play Services installed. It seem that it relies on these (external) sources for the location service. Excellent that habpanelviewer doesn't have such restrictions!

**Comment by MDAR** [comment]
I think it only needs the Google Play Services so the app can be loaded, you can delete / disable them once the app is on your machine, (I think, you'd need to chat  to the author for more details)

**Comment by aurelio1** [comment]
I am now using the [GPS Logger](https://play.google.com/store/apps/details?id=com.mendhak.gpslogger&hl=it) with the data delivered by the binding [GPS Tracker](https://www.openhab.org/addons/bindings/gpstracker/). It works without any problem.

**Comment by vbier** [comment]
As you found a workaround and I don't have the time for adding this, I close the issue.
